version: "3"

volumes:
  postgres_database :
     external: false
  schemas:
    external: false
services:
  web:
    image: nginx:latest
    container_name: "helium_nginx"
    ports:
      - "8000:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    links: ['php']
  php:
    container_name: "helium_php"
    build:
      context : ./
      dockerfile : Dockerfile
    volumes:
      - ./:/code
    depends_on: [ "postgres"]
  postgres:
    container_name: "helium_postgres"
    image: ntboes/postgres-uuid
    ports:
      - "5434:5432"
    volumes:
      - postgres_database:/var/postgres_database
    environment:
      - PGDATA=/var/postgres_database
      - POSTGRES_PASSWORD=helium_db
      - POSTGRES_USER=helium_db
      - POSTGRES_DB=helium_db
    restart: always
  redis:
    container_name: "helium_redis"
    image: redis:latest
    ports:
      - "6380:6379"